# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='cho_date',
            field=models.DateField(default='2017-10-01', verbose_name='date choice'),
            preserve_default=False,
        ),
    ]
