# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 09:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_cho_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='cho_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 9, 18, 23, 832000, tzinfo=utc), verbose_name='date choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 14, 9, 18, 23, 811000, tzinfo=utc), verbose_name='date published'),
        ),
    ]
