# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171114_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='cho_date',
            field=models.DateField(default='1900-01-01', verbose_name='date choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(default='1900-01-01', verbose_name='date published'),
        ),
    ]
