# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20171114_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qusetion_text',
            new_name='question_text',
        ),
    ]
