# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20171114_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_txt',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='question_id',
        ),
        migrations.AlterField(
            model_name='choice',
            name='cho_date',
            field=models.DateField(verbose_name='date choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_time',
            field=models.TimeField(),
        ),
    ]
