# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20171115_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_time',
        ),
        migrations.AlterField(
            model_name='choice',
            name='cho_date',
            field=models.DateTimeField(verbose_name='date choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
